import type { Metadata } from 'next'

import QueryProviders from "@/providers/query-provider"

export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProviders>
          {children}
        </QueryProviders>
      </body>
    </html>
  )
}
